[package]
name = "const_tensor"
version = "0.1.0"
edition = "2021"

[dependencies]
cudarc = { version = "0.11.4", features = ["cuda-12020"] }
thiserror = "1.0.61"

[build-dependencies]
bindgen_cuda = "0.1.5"