[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "target-cpu=native",
  "-C", "target-feature=+fp16"
]

[target.aarch64-apple-darwin]
[build]
rustflags = [
  "-C", "target-cpu=native",
  "-C", "target-feature=+fp16"
]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=-avx,-avx2"]